---
version: '2'
services:
    web:
        image: nginx
        ports:
            - 8080:80
        volumes:
            - ./conf.d:/etc/nginx/conf.d:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./store:/store:ro
            - ./static:/usr/share/nginx/html:ro
        volumes_from:
            - api
    api:
        build:
            context: ./api
        ports:
            - 5000:5000
        depends_on:
             - redis
        volumes:
            - ./api:/code
            - ./store:/store:rw
    redis:
        image: redis
        volumes:
            - svc_data:/data
            
volumes:
    svc_data: